/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and is checked in so the extracted source tree
// can build in a clean container.
